[tool.poetry]
name = "geometrics"
version = "0.1.0"
description = ""
authors = ["arsikurin <2024kurin.av@student.letovo.ru>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
