// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Courses         string
	CoursesProblems string
	Problems        string
	Submits         string
	Users           string
}{
	Courses:         "courses",
	CoursesProblems: "courses_problems",
	Problems:        "problems",
	Submits:         "submits",
	Users:           "users",
}
